sudo: false
language: cpp

compiler:
    - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-7
    - g++-7
    - libboost1.66-dev
    - libboost-filesystem1.66-dev

script: ./compile.sh

os:
    - linux
